<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find multi_legged_description)/urdf/common.xacro"/>
  <xacro:include filename="$(find multi_legged_description)/urdf/appendix/appendix.transmission.xacro"/>
  <xacro:include filename="$(find multi_legged_description)/urdf/appendix/appendix.gazebo.xacro"/>

  <xacro:macro name="appendix" params="prefix radius rho *joint_origin *joint_axis">
	<joint name="${prefix}_appendix_joint" type="revolute">
	  <insert_block name="joint_origin"/>
	  <parent link="${prefix}_tibia_link"/>
	  <child link="${prefix}_appendix_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
	  <limit lower="-0.0" upper="0.0" effort="100" velocity="100" />
	  <insert_block name="joint_axis"/>
	</joint>

	<link name="${prefix}_appendix_link">
	  <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <sphere radius="${radius}"/>
        </geometry>>
	  </visual>
	  <collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
		  <sphere radius="${radius}"/>
		</geometry>
	  </collision>
	  <inertial>
		<origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${rho * 0.75 * M_PI * radius * radius * radius}"/>
		<inertia
			ixx="${0.4 * rho * 0.75 * M_PI * radius * radius *  radius * radius * radius}" ixy="0.0" ixz="0.0"
			iyy="${0.4 * rho * 0.75 * M_PI * radius * radius *  radius * radius * radius}" iyz="0.0"
			izz="${0.4 * rho * 0.75 * M_PI * radius * radius *  radius * radius * radius}"/>
      </inertial>
	</link>
  </xacro:macro>
  
</robot>