<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find multi_legged_description)/urdf/common.xacro"/>
  <xacro:include filename="$(find multi_legged_description)/urdf/thigh/thigh.transmission.xacro"/>
  <xacro:include filename="$(find multi_legged_description)/urdf/thigh/thigh.gazebo.xacro"/>

  <property name="thigh_radius" value="0.03"/>
  <property name="thigh_length" value="0.2"/>
  <property name="thigh_mass" value="0.6"/>
  
  <xacro:macro name="thigh" params="prefix *joint_origin *joint_axis">
	<joint name="${prefix}_thigh_joint" type="continuous">
	  <insert_block name="joint_origin"/>
	  <parent link="${prefix}_base_clause_link"/>
	  <child link="${prefix}_thigh_link"/>
      <origin xyz="0 -0.003 0" rpy="0 0 0"/>
	  <insert_block name="joint_axis"/>
	</joint>
	<link name="${prefix}_thigh_link">
	  <visual>
        <origin xyz="0 -0.003 ${-thigh_length/2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${thigh_radius}" length="${thigh_length}"/>
        </geometry>>
	  </visual>
	  <collision>
		<origin xyz="0 -0.003 ${-thigh_length/2}" rpy="0 0 0"/>
		<geometry>
		  <cylinder radius="${thigh_radius}" length="${thigh_length/2}"/>
		</geometry>
	  </collision>
	  <inertial>
		<origin xyz="0 -0.003 ${-thigh_length/2}" rpy="0 0 0"/>
		<cylinder_inertial mass="${thigh_mass}"
						   radius="${thigh_radius}" length="${thigh_length}"/>
	  </inertial>
	</link>
  </xacro:macro>
  
</robot>