<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find multi_legged_description)/urdf/common.xacro"/>
  <xacro:include filename="$(find multi_legged_description)/urdf/thigh/thigh.transmission.xacro"/>
  <xacro:include filename="$(find multi_legged_description)/urdf/thigh/thigh.gazebo.xacro"/>
  
  <xacro:macro name="thigh" params="prefix radius length rho torque velocity *joint_origin *joint_axis">
	<joint name="${prefix}_thigh_joint" type="revolute">
	  <insert_block name="joint_origin"/>
	  <parent link="${prefix}_base_clause_link"/>
	  <child link="${prefix}_thigh_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
	  <limit lower="${-M_PI}" upper="${M_PI}" effort="${torque}" velocity="${velocity}" />
	  <insert_block name="joint_axis"/>
	</joint>
	<link name="${prefix}_thigh_link">
	  <visual>
        <origin xyz="${length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
        <geometry>
            <cylinder radius="${radius}" length="${length}"/>
        </geometry>
	  </visual>
	  <collision>
		<origin xyz="${length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
		<geometry>
		  <cylinder radius="${radius}" length="${length}"/>
		</geometry>
	  </collision>
	  <inertial>
		<origin xyz="${length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
		<cylinder_inertial mass="${rho * radius * radius * M_PI * length}"
						   radius="${radius}" length="${length}"/>
	  </inertial>
	</link>
  </xacro:macro>
  
</robot>