<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find multi_legged_description)/urdf/common.xacro"/>
  <xacro:include filename="$(find multi_legged_description)/urdf/thigh/thigh.transmission.xacro"/>
  <xacro:include filename="$(find multi_legged_description)/urdf/thigh/thigh.gazebo.xacro"/>
  
  <xacro:macro name="thigh" params="prefix radius length mass *joint_origin *joint_axis">
	<joint name="${prefix}_thigh_joint" type="continuous">
	  <insert_block name="joint_origin"/>
	  <parent link="${prefix}_base_clause_link"/>
	  <child link="${prefix}_thigh_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
	  <insert_block name="joint_axis"/>
	</joint>
	<link name="${prefix}_thigh_link">
	  <visual>
        <origin xyz="0 0 ${-length/2}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${radius}" length="${length}"/>
        </geometry>>
	  </visual>
	  <collision>
		<origin xyz="0 0 ${-length/2}" rpy="0 0 0"/>
		<geometry>
		  <cylinder radius="${radius}" length="${length}"/>
		</geometry>
	  </collision>
	  <inertial>
		<origin xyz="0 0 ${-length/2}" rpy="0 0 0"/>
		<cylinder_inertial mass="${mass}"
						   radius="${radius}" length="${length}"/>
	  </inertial>
	</link>
  </xacro:macro>
  
</robot>